OBJS = AMPT.o analysis.o
EXE = analysis

ROOTCFLAGS    = $(shell root-config --cflags)
ROOTLIBS      = $(shell root-config --libs)
ROOTGLIBS     = $(shell root-config --glibs)

INCFLAGS = -I$(ROOTSYS)/include
LDFLAGS = -L$(ROOTSYS)/lib

CXX = g++
FLAGS = -Wall -g -std=c++11 $(INCFLAGS) $(LDFLAGS)

COMPILE = $(CXX) $(FLAGS) -c

all: $(EXE)

$(EXE): $(OBJS)
	$(CXX) -o $(EXE) $(OBJS) $(ROOTFLAGS) $(ROOTLIBS)

%.o: %.cxx
	$(COMPILE)  $<

.PHONY : clean
clean :
	-rm -f $(OBJS) $(EXE)
